# Usa la imagen oficial de MySQL
FROM mysql:8.0.22

# Configura la base de datos
ENV MYSQL_ROOT_PASSWORD=1317
ENV MYSQL_DATABASE=parcial_db
ENV MYSQL_USER=marlon
ENV MYSQL_PASSWORD=1317

# Expone el puerto de MySQL
EXPOSE 3306